[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImageGeoms = "9ee76f2b-840d-4475-b6d6-e485c9297852"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LazyGrids = "7031d0ef-c40d-4431-b2f8-61a8d2f650db"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MIRTjim = "170b2178-6dee-4cb0-8729-b3e8b57834cc"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ImageGeoms = "0.11"
